urls:
- https://ya.ru
- https://github.com
- https://www.google.com
- http://ogp.me/ns#"
- https://www.ya.ru"
- https://cloud.yandex.ru/services/smartcaptcha?utm_source=captcha&amp;utm_medium=chbx&amp;utm_campaign=security"
- https://mail.google.com/mail/&amp;ogbl"
- https://www.google.com/imghp?hl=ru&amp;ogbl"
- https://www.google.ru/intl/ru/about/products"
- https://ssl.gstatic.com/gb/images/bar/al-icon.png"
- http://www.w3.org/2000/svg"><path
- https://lens.google.com"
- http://www.w3.org/2000/svg"><rect
user_agents:
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/113.0.0.0 Safari/537.36
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/113.0.0.0 Safari/537.36
rate_limit: 1
timeout: 30
max_retries: 3
websocket_timeout: 10
torrent_link: "magnet:?xt=urn:btih:723924A57607F3C926A644271E5B40BDF0B36F29&dn=IObit+Driver+Booster+Pro+12.0.0.308+Cracked+-+%5BCZSofts%5D&tr=http%3A%2F%2Fbt02.nnm-club.cc%3A2710%2F00b89bb6cf2713fa8a7b67da0f5dc8ee%2Fannounce&tr=http%3A%2F%2Fbt02.nnm-club.info%3A2710%2F00b89bb6cf2713fa8a7b67da0f5dc8ee%2Fannounce&tr=http%3A%2F%2Fretracker.local%2Fannounce.php%3Fsize%3D31539444%26comment%3Dhttp%253A%252F%252Fnnmclub.to%252Fforum%252Fviewtopic.php%253Fp%253D12483744%26name%3DIObit%2BDriver%2BBooster%2BPro%2B12.0.0.308%2BRePack%2B%2528%2526amp%253B%2BPortable%2529%2Bby%2BTryRooM%2B%255BMulti%252FRu%255D&tr=http%3A%2F%2Fbt02.ipv6.nnm-club.cc%3A2710%2F00b89bb6cf2713fa8a7b67da0f5dc8ee%2Fannounce&tr=http%3A%2F%2Fbt02.ipv6.nnm-club.info%3A2710%2F00b89bb6cf2713fa8a7b67da0f5dc8ee%2Fannounce&tr=http%3A%2F%2F%5B2a01%3Ad0%3Aa580%3A1%3A%3A2%5D%3A2710%2F00b89bb6cf2713fa8a7b67da0f5dc8ee%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce"